<?php
define('URL','http://localhost:8012/APIREST');
//define('URL','http://carlosmontenegro.es/APIREST');
define('HOST','localhost');
define('DB','logerroresweb');
define('USER','root');
define('PASSWORD',"");
define('CHARSET','utf8mb4');
?>